name: sixam_mart_delivery
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  audioplayers: ^5.2.1
  cached_network_image: ^3.3.0
  connectivity_plus: ^5.0.2
  country_code_picker: ^3.0.0
  cupertino_icons: ^1.0.8
  disable_battery_optimization: ^1.1.0+1
  dotted_border: ^2.0.0+1
  firebase_auth: ^4.20.0
  firebase_core: ^2.4.1
  firebase_messaging: ^14.7.10
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-alpha.5
  flutter_inappwebview: ^6.0.0
  flutter_local_notifications: ^17.2.1+2
  flutter_svg: ^2.0.10+1
  flutter_switch: ^0.3.2
  geocoding: ^2.0.0
  geolocator: ^10.1.0
  get: ^4.6.6
  google_maps_flutter: ^2.0.6
  http: ^1.2.1
  http_parser: ^4.0.2
  image_compression_flutter: ^1.0.4
  image_picker: ^1.0.7
  intl: ^0.19.0
  just_the_tooltip: ^0.0.12
  path: ^1.8.1
  path_provider: ^2.0.10
  phone_numbers_parser: ^8.1.0
  photo_view: ^0.14.0
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.0.6
  shimmer_animation: ^2.0.0
  url_launcher: ^6.1.2
  url_strategy: ^0.2.0
  vibration: ^1.7.6
  web_socket_channel: ^2.4.0
  win32: ^5.2.0
dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/notification.mp3

  fonts:
    - family: Almarai
      fonts:
        - asset: assets/font/Almarai-Regular.ttf
          weight: 400
        - asset: assets/font/Almarai-Light.ttf
          weight: 500
        - asset: assets/font/Almarai-Bold.ttf
          weight: 700
        - asset: assets/font/Almarai-ExtraBold.ttf
          weight: 900
